services:
   palworld:
      build: ./
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - MULTITHREADING=true
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - SERVER_NAME="World of Pals"
         - SERVER_PASSWORD="worldofpals"
         - ADMIN_PASSWORD="adminPasswordHere"
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=UTC
         - UPDATE_ON_BOOT=true
         - COMMUNITY=false
      volumes:
         - ./palworld:/palworld/